const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => { const response = await fetch(`/api/v1${path}`, options); if (!response.ok) throw new Error(await response.text()); return response.json(); };
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let lastEvent;

function showView(name) { document.querySelectorAll('.view').forEach(view => view.classList.toggle('active', view.id === `view-${name}`)); document.querySelectorAll('.nav').forEach(button => button.classList.toggle('active', button.dataset.view === name)); if (name === 'review') loadReview(); if (name === 'schedule') loadSchedule(); if (name === 'analytics') loadAnalytics(); if (name === 'audit') loadAudit(); }
document.querySelectorAll('.nav').forEach(button => button.addEventListener('click', () => showView(button.dataset.view)));
document.querySelectorAll('.sample').forEach(button => button.addEventListener('click', () => { $('#report-text').value = button.dataset.text; }));

async function refreshMetrics() { const activities = await api('/projects/1/activities'); const critical = activities.filter(a => a.critical); $('#activity-count').textContent = activities.length; $('#critical-count').textContent = critical.length; const audit = await api('/audit'); $('#report-count').textContent = new Set(audit.map(a => a.event_id)).size; }
async function submitReport(text = $('#report-text').value, source = 'text') { if (!text.trim()) return; const started = performance.now(); const result = await api('/reports', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({text, source})}); result.latency_ms = Math.round(performance.now() - started); lastEvent = result; $('#latency').textContent = `${result.latency_ms} ms`; renderResult(result); refreshMetrics(); }
function renderResult(result) { const m = result.match; $('#result').classList.remove('hidden'); $('#result').innerHTML = `<div class="eyebrow">${escapeHtml(m.decision)}</div><h3>${m.activity_id ? `Candidate activity #${m.activity_id}` : 'Observation preserved without a schedule link'}</h3><p>Top <strong>${m.top_score.toFixed(3)}</strong> · runner-up <strong>${m.second_score.toFixed(3)}</strong> · margin <strong>${m.margin.toFixed(3)}</strong></p><p class="muted">Source span: ${escapeHtml(result.event.source_text)}<br>Measured processing latency: ${result.latency_ms} ms</p><button class="ghost" onclick="showView('review')">Open evidence queue →</button>`; }
$('#submit-report').addEventListener('click', () => submitReport());
$('#voice').addEventListener('click', () => { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { $('#voice-status').textContent = 'Microphone unavailable · type instead'; return; } const recognition = new SpeechRecognition(); recognition.onstart = () => $('#voice-status').textContent = 'Listening...'; recognition.onresult = event => { $('#report-text').value = event.results[0][0].transcript; $('#voice-status').textContent = 'Transcript captured'; }; recognition.onerror = () => $('#voice-status').textContent = 'Microphone failed · type instead'; recognition.onend = () => $('#voice-status').textContent = 'Voice ready'; recognition.start(); });
$('#send-agent').addEventListener('click', async () => { const text = $('#agent-text').value.trim(); if (!text) return; $('#chat').insertAdjacentHTML('beforeend', `<div class="bubble user">${escapeHtml(text)}</div>`); $('#agent-text').value = ''; const result = await api('/agent/message', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({text, session_id:'browser-demo'})}); $('#chat').insertAdjacentHTML('beforeend', `<div class="bubble system">${escapeHtml(result.reply)} <strong>${escapeHtml(result.match.decision)}</strong> · margin ${result.match.margin.toFixed(3)}</div>`); $('#latency').textContent = `${result.latency_ms} ms`; refreshMetrics(); });

async function loadReview() { const queue = await api('/review-queue'); const root = $('#review-list'); if (!queue.length) { root.innerHTML = '<div class="panel"><h2>Queue clear</h2><p class="muted">New ambiguous or unmatched observations will appear here.</p></div>'; return; } root.innerHTML = ''; for (const event of queue) { const candidates = await api(`/events/${event.id}/candidates`); const top = candidates[0]; const card = document.createElement('article'); card.className = 'review-card'; card.innerHTML = `<div class="eyebrow">${escapeHtml(event.decision)} · event #${event.id}</div><h3>${escapeHtml(event.activity_terms)}</h3><pre>${escapeHtml(event.source_text)}</pre><div class="score-grid">${[['ID',top.score_id],['LEXICAL',top.score_lexical],['SEMANTIC',top.score_semantic],['CONTEXT',top.score_context]].map(([name,value]) => `<div class="score"><span>${name}</span><strong>${Number(value).toFixed(2)}</strong><div class="bar"><i style="width:${Number(value)*100}%"></i></div></div>`).join('')}</div><p class="muted">Top: ${Number(event.top_score).toFixed(3)} · runner-up: ${Number(event.second_score).toFixed(3)} · margin: ${Number(event.margin).toFixed(3)} · mapped terms: ${escapeHtml((top.evidence.mapped_terms || []).map(t => `${t.field_term} → ${t.canonical_term}`).join(', ') || 'none')}</p><div><strong>${escapeHtml(top.activity_code)} · ${escapeHtml(top.description)}</strong><span class="muted"> / ${escapeHtml(top.location)} / ${escapeHtml(top.wbs_path)}</span></div><div class="review-actions"><button class="primary compact" data-confirm="${event.id}" data-activity="${top.activity_id}">Approve top candidate</button><button class="secondary" data-reject="${event.id}">Reject</button></div>`; root.appendChild(card); } root.querySelectorAll('[data-confirm]').forEach(button => button.addEventListener('click', async () => { await api(`/events/${button.dataset.confirm}/confirm`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({activity_id:Number(button.dataset.activity), actor:'planner'})}); loadReview(); refreshMetrics(); })); root.querySelectorAll('[data-reject]').forEach(button => button.addEventListener('click', async () => { await api(`/events/${button.dataset.reject}/reject`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({actor:'planner'})}); loadReview(); })); }
async function loadSchedule() { const activities = await api('/projects/1/activities'); $('#schedule-table').innerHTML = activities.slice(0,25).map(a => `<tr><td><strong>${escapeHtml(a.activity_code)}</strong><br><span class="muted">${escapeHtml(a.description)}</span></td><td>${escapeHtml(a.discipline)}</td><td>${escapeHtml(a.planned_start)} → ${escapeHtml(a.planned_finish)}</td><td>${escapeHtml(a.actual_start || '—')}<br>${a.percent_complete}%</td><td class="${a.critical ? 'critical' : ''}">${Number(a.total_float || 0).toFixed(1)}d</td><td class="state">${a.at_risk ? 'AT RISK' : a.status}</td></tr>`).join(''); }
async function loadAnalytics() { const rows = await api('/analytics/discipline-productivity'); $('#discipline-bars').innerHTML = rows.map(row => `<div class="discipline-row"><header><span>${escapeHtml(row.discipline)}</span><strong>${row.progress || 0}%</strong></header><div class="wide-bar"><i style="width:${row.progress || 0}%"></i></div></div>`).join(''); const variance = await api('/analytics/variance'); $('#variance-list').innerHTML = variance.map(row => `<div class="memory-item"><strong>${escapeHtml(row.wbs_path)}</strong><small>${row.activities} activities · ${row.progress || 0}% average progress</small></div>`).join(''); }
async function loadAudit() { const rows = await api('/audit'); $('#audit-table').innerHTML = rows.map(row => `<tr><td>${escapeHtml(row.created_at)}</td><td>#${row.activity_id}</td><td>${escapeHtml(row.old_value)} → ${escapeHtml(row.new_value)}</td><td>${escapeHtml(row.evidence)}</td><td>${escapeHtml(row.actor)} · ${Number(row.score || 0).toFixed(2)}</td></tr>`).join('') || '<tr><td colspan="5">No confirmed updates yet.</td></tr>'; }
$('#search-memory').addEventListener('click', async () => { const rows = await api(`/memory/similar?description=${encodeURIComponent($('#memory-query').value)}`); $('#memory-results').innerHTML = rows.map(row => `<div class="memory-item"><strong>${escapeHtml(row.activity_code)} · ${escapeHtml(row.description)}</strong><small>${escapeHtml(row.discipline)} · similarity ${Number(row.similarity).toFixed(2)} · actual duration ${row.actual_duration} days</small></div>`).join('') || '<p class="muted">No historical executions yet.</p>'; });
refreshMetrics();
